AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Parameters:
  HostedZoneId:
    Description: Route 53 Hosted Zone ID
    Type: String
    Default: Z1048063LC3J2IKH5GGI

Resources:
  SortFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: rust-cargolambda # More info about Cargo Lambda: https://github.com/cargo-lambda/cargo-lambda
    Properties:
      CodeUri: ./rust_app   # Points to dir of Cargo.toml
      Handler: bootstrap    # Do not change, as this is the default executable name produced by Cargo Lambda
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        Post:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref Api
  
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: api.yell.brendandagys.com
      DomainValidationOptions:
        - DomainName: api.yell.brendandagys.com
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref AWS::StackName
      StageName: Prod
      Cors:
        AllowOrigin: "'yell.brendandagys.com'"
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type, X-Forwarded-For'"
      Domain:
        DomainName: !Sub api.yell.brendandagys.com
        CertificateArn: !Ref Certificate
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostedZoneId

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: yell.brendandagys.com
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  DnsRecordToFrontend:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: yell.brendandagys.com
      Type: A
      AliasTarget:
        HostedZoneId: Z3AQBSTGFYJSTF # us-east-1 S3 Hosted Zone ID
        DNSName: !GetAtt WebsiteBucket.DomainName

  DnsRecordToBackend:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: api.yell.brendandagys.com
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # us-east-1 API Gateway Hosted Zone ID
        DNSName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
