AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  HostedZoneId:
    Default: Z1048063LC3J2IKH5GGI
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: api.yell.brendandagys.com
      DomainValidationOptions:
        - DomainName: api.yell.brendandagys.com
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  Api:
    Type: AWS::Serverless::Api
    # DependsOn: Certificate
    Properties:
      Name: !Ref AWS::StackName
      StageName: Prod
      Domain:
        DomainName: !Sub api.yell.brendandagys.com
        CertificateArn: !Ref Certificate
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostedZoneId
  
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_app   # Points to dir of Cargo.toml
      Handler: bootstrap    # Don't change this default executable name from Cargo Lambda
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref Api

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: yell.brendandagys.com
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  DnsRecordToFrontend:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: yell.brendandagys.com
      Type: A
      AliasTarget:
        HostedZoneId: Z3AQBSTGFYJSTF # us-east-1 S3 Hosted Zone ID
        DNSName: s3-website-us-east-1.amazonaws.com
