AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Conditions:
  CreateSlowResources: !Equals [1,0]

Parameters:
  CertificateArn:
    Default: arn:aws:acm:us-east-1:708746137251:certificate/17b38c0f-ac70-4643-a6bd-2e5a57719ba7
    Type: String
  Domain:
    Default: sort.brendandagys.com
    Type: String
  HostedZoneId:
    Default: Z1048063LC3J2IKH5GGI
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref AWS::StackName
      StageName: Prod
      Domain:
        DomainName: !Sub api.${Domain}
        CertificateArn: !If [CreateSlowResources, !Ref Certificate, !Ref CertificateArn]
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostedZoneId
  ##############################################################################
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_app  # Points to dir of Cargo.toml
      Handler: bootstrap   # Don't change this default executable name from Cargo Lambda
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        SendMessage:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref Api
  ##############################################################################
  WebsiteBucket:
    Condition: CreateSlowResources
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false # CloudFront and CodeBuild use ACLs
        IgnorePublicAcls: false
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  ##############################################################################
  WebsiteBucketPolicy:
    Condition: CreateSlowResources
    DeletionPolicy: Retain
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*
          Condition:
            StringEquals:
              AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AppDistribution}
  ##############################################################################
  DnsRecordToFrontend:
    Condition: CreateSlowResources
    DeletionPolicy: Retain
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Domain
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Always this when creating an alias record that routes traffic to a CloudFront distribution
        DNSName: !GetAtt AppDistribution.DomainName
  
  ##############################################################################
  #####                      OPTIONAL - allows for HTTPS                   #####
  ##############################################################################

  Certificate:
    Condition: CreateSlowResources
    DeletionPolicy: Retain
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      SubjectAlternativeNames:
        - !Sub '*.${Domain}'
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
  ##############################################################################
  OriginAccessControl:
    Condition: CreateSlowResources
    DeletionPolicy: Retain
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  ##############################################################################
  AppDistribution:
    Condition: CreateSlowResources
    DeletionPolicy: Retain
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref Domain
        Origins:
          - Id: !Ref Domain
            DomainName: !Sub ${AWS::StackName}.s3.${AWS::Region}.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Ref Domain
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
